apiVersion: v1
kind: ServiceAccount
metadata:
  name: novai-service-account
  namespace: novai-production
  annotations:
    iam.gke.io/gcp-service-account: novai-compute@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novai-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: novai-service-account
    namespace: novai-production
